interface Section {
  title: string
  content: string
  items?: string[]
}

const en: Section[] = [
  { title: "Introduction", content: "We have developed this privacy policy to provide comprehensive information about collecting and using your Personally Identifiable Information (PII) online, per UAE privacy law and information security guidelines. PII refers to data that can be used, either alone or in combination with other information, to identify, contact, or locate an individual, or to identify an individual within a particular context. It is crucial that you carefully review our privacy policy to gain a clear understanding of how, why, and when we collect your Personally Identifiable Information through our website. This Service Privacy Notice also outlines your rights regarding collecting this data, including the option to opt out of interest-based advertising, also known as targeted or personalized advertising." },
  { title: "What personal information do we collect?", content: "When registering on our site, you may be asked to enter your name, email address, phone number or other details to help you with your experience." },
  { title: "When do we collect information?", content: "We collect information from you when you register on our site, subscribe to a newsletter, fill out a form, use live chat or enter information on our site." },
  { title: "How do we use your information?", content: "We may use the information we collect from you when you register, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:", items: ["To personalize your experience and to allow us to deliver the type of content and project offerings in which you are most interested.", "To send periodic emails regarding your project interests or other services.", "To follow up with them after correspondence (live chat, email or phone inquiries)."] },
  { title: "How do we protect your information?", content: "Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible. We use regular Malware Scanning. We never ask for personal or private information like credit card numbers." },
  { title: "Do we use cookies?", content: "We do not use cookies for tracking purposes. You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since each browser is a little different, look at your browser's Help Menu to learn the correct way to modify your cookies. If you turn cookies off, some features will be disabled that make your site experience more efficient and may not function properly. However, you will still be able to register your interest." },
  { title: "Third-party disclosure", content: "We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information." },
  { title: "Third-party links", content: "We do not include or offer third-party services on our website." },
  { title: "Google", content: "Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. We use Google AdSense Advertising on our website. Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy." },
  { title: "We have implemented the following:", content: "", items: ["Remarketing with Google AdSense", "Google Display Network Impression Reporting"] },
  { title: "", content: "We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website." },
  { title: "Opting out", content: "Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising Initiative Opt Out page or by using the Google Analytics Opt Out Browser add on." },
  { title: "UAE Online Privacy Protection Act", content: "The law's reach stretches well beyond UAE to require any person or company in the GCC (and conceivably the world) that operates websites collecting Personally Identifiable Information from UAE consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. According to the law, we agree to the following:", items: ["Users can visit our site anonymously.", "Once this privacy policy is created, we will add a link to it on our home page or as a minimum, on the first significant page after entering our website.", "Our Privacy Policy link includes the word 'Privacy' and can easily be found on the page specified above.", "You will be notified of any Privacy Policy changes on our Privacy Policy Page.", "You can change your personal information by emailing us, by chatting with us or by sending us a support ticket."] },
  { title: "How does our site handle Do Not Track signals?", content: "We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place." },
  { title: "Does our site allow third-party behavioral tracking?", content: "It's also important to note that we allow third-party behavioral tracking." },
  { title: "COPPA (Children Online Privacy Protection Act)", content: "When it comes to the collection of personal information from children under the age of 13 years old, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online. We do not specifically market to children under the age of 13 years old." },
  { title: "Fair Information Practices", content: "The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information. In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:", items: ["We will notify you via email within 1 business day."] },
  { title: "", content: "We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors." },
  { title: "What Personal Data is Collected and How Personal Data is Collected", content: "We collect information from you when you register on our site, subscribe to a newsletter, fill out a form, use live chat, or enter information on our site. We collect personal data, such as visitor IP addresses, from visitors to our site using tracking technologies such as third-party cookies and non-cookie technologies. We may use the information we collect from you when you register, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:", items: ["To personalize your experience and allow us to deliver the type of content and project offerings you are most interested in.", "To send periodic emails regarding your project interests or other services.", "To follow up with them after correspondence (live chat, email, or phone inquiries)."] },
  { title: "Purposes for Which the Data is Used and by Whom", content: "We collect your emails for direct marketing purposes. When you register, subscribe to our newsletter, participate in a survey or marketing communication, browse our website, or utilize specific features, we collect information from you. This information is utilized in the following ways:", items: ["Personalization: We strive to tailor your experience and deliver content and project offerings that align with your interests.", "Communication: We send periodic emails about your project interests or other valuable services.", "Follow-up: We reach out to provide further assistance and address any inquiries you may have, be it through live chat, email, or phone."] },
  { title: "How Visitors Can Control the Collection of Their Data", content: "Please note that you can control data collection through your web browser and mobile device. We provide the following instructions to help you exercise this control:" },
  { title: "For Web Browsers", content: "Declining Third-Party Cookies: Navigate to the settings feature in your web browser and choose to reject all third-party cookies. Alternatively, you can specifically decline third-party cookies from specific websites." },
  { title: "For Mobile Devices", content: "Limiting Ad Tracking: Access the privacy settings on your mobile device and locate the option to limit ad tracking. Enable this setting to restrict the collection of data for targeted advertising purposes. Resetting Advertiser Identifier: In the privacy settings of your mobile device, you may find the option to reset the advertiser identifier. This action will reset the unique identifier associated with your device, helping to limit the tracking of your data for targeted advertising." },
  { title: "How do we use the Data we collect?", content: "Our objective is to utilize this data in order to accurately identify and connect with you, thereby offering an optimal online experience where ad-supported content is accessible at no cost, and the advertisements presented to you are relevant and engaging. Furthermore, we employ this data to effectively operate, enhance, and improve our services." },
  { title: "Cross-device matching", content: "By identifying various devices and browsers associated with you, we can strategically target, regulate, and sequence advertisements, allowing us to effectively measure and analyze campaign performance. For instance, this cross-device matching enables us to avoid showing you ads for a property you have already searched on one device, such as your tablet, after viewing them on your phone. Instead, we can present you with advertisements for upcoming property launches where you can utilize those interests. Additionally, this matching process ensures that your opt-out preferences are recognized across all connected devices, providing a consistent experience. To opt out of cross-device interest-based targeting, please utilize the relevant opt-out methods available to you." },
  { title: "Segmenting Audiences", content: "We employ segmentation techniques to categorize individuals into specific groups based on their demographic and firmographic information linked to their unique identifier. This segmentation enables us to generate insightful reports and conduct thorough analytics. It also helps us determine the most relevant ads and email content that aligns with your specific interests. If you are visiting our website from the USA, rest assured that all data collection activities adhere to the provisions outlined in the California Privacy Rights Act (CPRA). For visitors from Europe, the General Data Protection Regulation (GDPR) applies, and as a result, you are considered a GDPR-impacted customer." },
  { title: "CAN SPAM Act", content: "The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations. We collect your email address in order to be in accordance with CANSPAM. If at any time you would like to unsubscribe from receiving future emails, you can email us at info@offplan-dubai.com and we will promptly remove you from ALL correspondence." },
  { title: "Contacting Us", content: "If there are any questions regarding this privacy policy, you may contact us using the information below.\n\nOffice #1802, 18th Floor, Marina Plaza, Dubai Marina, Dubai, UAE\n\ninfo@providentestate.com" },
]

const es: Section[] = [
  { title: "Introducción", content: "Hemos desarrollado esta política de privacidad para proporcionar información completa sobre la recopilación y el uso de su Información de Identificación Personal (PII) en línea, según la ley de privacidad de los EAU y las directrices de seguridad de la información. La PII se refiere a datos que pueden usarse, solos o en combinación con otra información, para identificar, contactar o localizar a un individuo, o para identificar a un individuo dentro de un contexto particular. Es crucial que revise cuidadosamente nuestra política de privacidad para obtener una comprensión clara de cómo, por qué y cuándo recopilamos su Información de Identificación Personal a través de nuestro sitio web." },
  { title: "¿Qué información personal recopilamos?", content: "Al registrarse en nuestro sitio, es posible que se le solicite ingresar su nombre, dirección de correo electrónico, número de teléfono u otros detalles para ayudarle con su experiencia." },
  { title: "¿Cuándo recopilamos información?", content: "Recopilamos información suya cuando se registra en nuestro sitio, se suscribe a un boletín informativo, completa un formulario, utiliza el chat en vivo o ingresa información en nuestro sitio." },
  { title: "¿Cómo usamos su información?", content: "Podemos usar la información que recopilamos de usted cuando se registra, se suscribe a nuestro boletín, responde a una encuesta o comunicación de marketing, navega por el sitio web o utiliza ciertas otras funciones del sitio de las siguientes maneras:", items: ["Para personalizar su experiencia y permitirnos entregar el tipo de contenido y ofertas de proyectos en los que está más interesado.", "Para enviar correos electrónicos periódicos sobre sus intereses de proyectos u otros servicios.", "Para hacer seguimiento después de la correspondencia (chat en vivo, correo electrónico o consultas telefónicas)."] },
  { title: "¿Cómo protegemos su información?", content: "Nuestro sitio web se escanea regularmente en busca de agujeros de seguridad y vulnerabilidades conocidas para que su visita a nuestro sitio sea lo más segura posible. Utilizamos escaneo regular de malware. Nunca solicitamos información personal o privada como números de tarjetas de crédito." },
  { title: "¿Usamos cookies?", content: "No utilizamos cookies con fines de seguimiento. Puede elegir que su computadora le advierta cada vez que se envía una cookie, o puede optar por desactivar todas las cookies. Hace esto a través de la configuración de su navegador. Dado que cada navegador es un poco diferente, consulte el Menú de Ayuda de su navegador para conocer la forma correcta de modificar sus cookies. Si desactiva las cookies, algunas funciones se desactivarán y pueden no funcionar correctamente. Sin embargo, aún podrá registrar su interés." },
  { title: "Divulgación a terceros", content: "No vendemos, intercambiamos ni transferimos a terceros su Información de Identificación Personal." },
  { title: "Enlaces a terceros", content: "No incluimos ni ofrecemos servicios de terceros en nuestro sitio web." },
  { title: "Google", content: "Los requisitos publicitarios de Google se pueden resumir en los Principios de Publicidad de Google. Están establecidos para proporcionar una experiencia positiva para los usuarios. Utilizamos Google AdSense en nuestro sitio web. Google, como proveedor externo, utiliza cookies para mostrar anuncios en nuestro sitio. El uso de la cookie DART por parte de Google le permite mostrar anuncios a nuestros usuarios basados en visitas previas a nuestro sitio y otros sitios en Internet. Los usuarios pueden optar por no usar la cookie DART visitando la política de privacidad de la Red de Contenido y Anuncios de Google." },
  { title: "Hemos implementado lo siguiente:", content: "", items: ["Remarketing con Google AdSense", "Informes de impresiones de la Red de Display de Google"] },
  { title: "", content: "Nosotros, junto con proveedores externos como Google, utilizamos cookies propias (como las cookies de Google Analytics) y cookies de terceros (como la cookie DoubleClick) u otros identificadores de terceros juntos para recopilar datos sobre las interacciones de los usuarios con las impresiones de anuncios y otras funciones del servicio de anuncios en relación con nuestro sitio web." },
  { title: "Exclusión voluntaria", content: "Los usuarios pueden establecer preferencias sobre cómo Google le anuncia utilizando la página de Configuración de Anuncios de Google. Alternativamente, puede optar por no participar visitando la página de Exclusión Voluntaria de la Iniciativa de Publicidad en Red o utilizando el complemento del navegador de Exclusión Voluntaria de Google Analytics." },
  { title: "Ley de Protección de Privacidad en Línea de los EAU", content: "El alcance de la ley se extiende mucho más allá de los EAU para exigir que cualquier persona o empresa en el CCG (y posiblemente en el mundo) que opere sitios web que recopilen Información de Identificación Personal de consumidores de los EAU publique una política de privacidad visible en su sitio web indicando exactamente la información que se recopila y las personas o empresas con las que se comparte. De acuerdo con la ley, acordamos lo siguiente:", items: ["Los usuarios pueden visitar nuestro sitio de forma anónima.", "Una vez creada esta política de privacidad, agregaremos un enlace a ella en nuestra página de inicio o, como mínimo, en la primera página significativa después de ingresar a nuestro sitio web.", "El enlace de nuestra Política de Privacidad incluye la palabra 'Privacidad' y se puede encontrar fácilmente en la página especificada anteriormente.", "Se le notificará de cualquier cambio en la Política de Privacidad en nuestra Página de Política de Privacidad.", "Puede cambiar su información personal enviándonos un correo electrónico, chateando con nosotros o enviándonos un ticket de soporte."] },
  { title: "¿Cómo maneja nuestro sitio las señales de No Rastrear?", content: "Honramos las señales de No Rastrear y No Rastrear, plantamos cookies o utilizamos publicidad cuando un mecanismo de navegador de No Rastrear (DNT) está activo." },
  { title: "¿Permite nuestro sitio el seguimiento conductual de terceros?", content: "También es importante tener en cuenta que permitimos el seguimiento conductual de terceros." },
  { title: "COPPA (Ley de Protección de la Privacidad Infantil en Línea)", content: "Cuando se trata de la recopilación de información personal de niños menores de 13 años, la Ley de Protección de la Privacidad Infantil en Línea (COPPA) otorga a los padres el control. La Comisión Federal de Comercio, la agencia de protección al consumidor de Estados Unidos, hace cumplir la Regla COPPA, que detalla lo que los operadores de sitios web y servicios en línea deben hacer para proteger la privacidad y seguridad de los niños en línea. No comercializamos específicamente a niños menores de 13 años." },
  { title: "Prácticas de Información Justa", content: "Los Principios de Prácticas de Información Justa forman la columna vertebral de la ley de privacidad en los Estados Unidos y los conceptos que incluyen han desempeñado un papel importante en el desarrollo de las leyes de protección de datos en todo el mundo. Comprender los Principios de Prácticas de Información Justa y cómo deben implementarse es fundamental para cumplir con las diversas leyes de privacidad que protegen la información personal. Para estar en línea con las Prácticas de Información Justa, tomaremos la siguiente acción de respuesta, en caso de una violación de datos:", items: ["Le notificaremos por correo electrónico dentro de 1 día hábil."] },
  { title: "", content: "También aceptamos el Principio de Reparación Individual que requiere que las personas tengan el derecho de perseguir legalmente derechos ejecutables contra los recopiladores y procesadores de datos que no cumplan con la ley. Este principio requiere no solo que las personas tengan derechos ejecutables contra los usuarios de datos, sino también que las personas tengan recurso a tribunales o agencias gubernamentales para investigar y/o procesar el incumplimiento por parte de los procesadores de datos." },
  { title: "Qué Datos Personales se Recopilan y Cómo se Recopilan", content: "Recopilamos información de usted cuando se registra en nuestro sitio, se suscribe a un boletín informativo, completa un formulario, utiliza el chat en vivo o ingresa información en nuestro sitio. Recopilamos datos personales, como direcciones IP de visitantes, de los visitantes de nuestro sitio utilizando tecnologías de seguimiento como cookies de terceros y tecnologías no basadas en cookies. Podemos usar la información que recopilamos de usted cuando se registra, se suscribe a nuestro boletín, responde a una encuesta o comunicación de marketing, navega por el sitio web o utiliza ciertas otras funciones del sitio de las siguientes maneras:", items: ["Para personalizar su experiencia y permitirnos ofrecer el tipo de contenido y ofertas de proyectos que más le interesan.", "Para enviar correos electrónicos periódicos sobre sus intereses de proyectos u otros servicios.", "Para hacer seguimiento después de la correspondencia (chat en vivo, correo electrónico o consultas telefónicas)."] },
  { title: "Fines para los que se Utilizan los Datos y por Quién", content: "Recopilamos sus correos electrónicos con fines de marketing directo. Cuando se registra, se suscribe a nuestro boletín, participa en una encuesta o comunicación de marketing, navega por nuestro sitio web o utiliza funciones específicas, recopilamos información suya. Esta información se utiliza de las siguientes maneras:", items: ["Personalización: Nos esforzamos por adaptar su experiencia y ofrecer contenido y ofertas de proyectos que se alineen con sus intereses.", "Comunicación: Enviamos correos electrónicos periódicos sobre sus intereses de proyectos u otros servicios valiosos.", "Seguimiento: Nos comunicamos para brindar asistencia adicional y abordar cualquier consulta que pueda tener, ya sea a través de chat en vivo, correo electrónico o teléfono."] },
  { title: "Cómo Pueden los Visitantes Controlar la Recopilación de sus Datos", content: "Tenga en cuenta que puede controlar la recopilación de datos a través de su navegador web y dispositivo móvil. Proporcionamos las siguientes instrucciones para ayudarle a ejercer este control:" },
  { title: "Para Navegadores Web", content: "Rechazar Cookies de Terceros: Navegue hasta la función de configuración de su navegador web y elija rechazar todas las cookies de terceros. Alternativamente, puede rechazar específicamente las cookies de terceros de sitios web específicos." },
  { title: "Para Dispositivos Móviles", content: "Limitar el Seguimiento de Anuncios: Acceda a la configuración de privacidad en su dispositivo móvil y localice la opción para limitar el seguimiento de anuncios. Active esta configuración para restringir la recopilación de datos con fines publicitarios dirigidos. Restablecer el Identificador del Anunciante: En la configuración de privacidad de su dispositivo móvil, puede encontrar la opción para restablecer el identificador del anunciante. Esta acción restablecerá el identificador único asociado con su dispositivo, ayudando a limitar el seguimiento de sus datos para publicidad dirigida." },
  { title: "¿Cómo usamos los Datos que recopilamos?", content: "Nuestro objetivo es utilizar estos datos para identificarlo y conectarnos con usted con precisión, ofreciendo así una experiencia en línea óptima donde el contenido respaldado por anuncios sea accesible sin costo, y los anuncios que se le presenten sean relevantes y atractivos. Además, empleamos estos datos para operar, mejorar y perfeccionar nuestros servicios de manera efectiva." },
  { title: "Coincidencia entre dispositivos", content: "Al identificar varios dispositivos y navegadores asociados con usted, podemos orientar, regular y secuenciar anuncios estratégicamente, lo que nos permite medir y analizar el rendimiento de la campaña de manera efectiva. Por ejemplo, esta coincidencia entre dispositivos nos permite evitar mostrarle anuncios de una propiedad que ya ha buscado en un dispositivo, como su tableta, después de verlos en su teléfono. En su lugar, podemos presentarle anuncios de próximos lanzamientos de propiedades donde pueda utilizar esos intereses. Además, este proceso de coincidencia garantiza que sus preferencias de exclusión voluntaria sean reconocidas en todos los dispositivos conectados, brindando una experiencia consistente." },
  { title: "Segmentación de Audiencias", content: "Empleamos técnicas de segmentación para categorizar a las personas en grupos específicos basados en su información demográfica y firma gráfica vinculada a su identificador único. Esta segmentación nos permite generar informes perspicaces y realizar análisis exhaustivos. También nos ayuda a determinar los anuncios y contenidos de correo electrónico más relevantes que se alinean con sus intereses específicos." },
  { title: "Ley CAN SPAM", content: "La Ley CAN-SPAM es una ley que establece las reglas para el correo electrónico comercial, establece requisitos para los mensajes comerciales, otorga a los destinatarios el derecho de que se les deje de enviar correos electrónicos y establece duras penalizaciones por violaciones. Recopilamos su dirección de correo electrónico para estar en conformidad con CAN-SPAM. Si en algún momento desea darse de baja para no recibir futuros correos electrónicos, puede enviarnos un correo electrónico a info@offplan-dubai.com y lo eliminaremos rápidamente de TODA correspondencia." },
  { title: "Contacto", content: "Si tiene alguna pregunta sobre esta política de privacidad, puede contactarnos utilizando la siguiente información.\n\nOficina #1802, 18.º Piso, Marina Plaza, Dubai Marina, Dubái, EAU\n\ninfo@providentestate.com" },
]

const pt: Section[] = [
  { title: "Introdução", content: "Desenvolvemos esta política de privacidade para fornecer informações abrangentes sobre a recolha e utilização das suas Informações Pessoais Identificáveis (PII) online, de acordo com a lei de privacidade dos EAU e as diretrizes de segurança da informação. PII refere-se a dados que podem ser usados, isoladamente ou em combinação com outras informações, para identificar, contactar ou localizar um indivíduo, ou para identificar um indivíduo num contexto particular. É crucial que reveja cuidadosamente a nossa política de privacidade para obter uma compreensão clara de como, porquê e quando recolhemos as suas Informações Pessoais Identificáveis através do nosso site." },
  { title: "Que informações pessoais recolhemos?", content: "Ao registar-se no nosso site, poderá ser solicitado a inserir o seu nome, endereço de e-mail, número de telefone ou outros detalhes para ajudar na sua experiência." },
  { title: "Quando recolhemos informações?", content: "Recolhemos informações suas quando se regista no nosso site, subscreve uma newsletter, preenche um formulário, utiliza o chat ao vivo ou insere informações no nosso site." },
  { title: "Como usamos as suas informações?", content: "Podemos usar as informações que recolhemos de si quando se regista, subscreve a nossa newsletter, responde a um inquérito ou comunicação de marketing, navega no site ou utiliza certas outras funcionalidades do site das seguintes formas:", items: ["Para personalizar a sua experiência e permitir-nos fornecer o tipo de conteúdo e ofertas de projetos em que está mais interessado.", "Para enviar e-mails periódicos sobre os seus interesses em projetos ou outros serviços.", "Para fazer follow-up após correspondência (chat ao vivo, e-mail ou consultas telefónicas)."] },
  { title: "Como protegemos as suas informações?", content: "O nosso site é analisado regularmente em busca de falhas de segurança e vulnerabilidades conhecidas para tornar a sua visita ao nosso site o mais segura possível. Utilizamos verificação regular de malware. Nunca solicitamos informações pessoais ou privadas como números de cartão de crédito." },
  { title: "Usamos cookies?", content: "Não utilizamos cookies para fins de rastreamento. Pode optar por que o seu computador o avise sempre que um cookie for enviado, ou pode optar por desativar todos os cookies. Faz isso através das configurações do seu navegador. Como cada navegador é um pouco diferente, consulte o Menu de Ajuda do seu navegador para saber a forma correta de modificar os seus cookies. Se desativar os cookies, algumas funcionalidades serão desativadas e podem não funcionar corretamente. No entanto, ainda poderá registar o seu interesse." },
  { title: "Divulgação a terceiros", content: "Não vendemos, trocamos ou transferimos para terceiros as suas Informações Pessoais Identificáveis." },
  { title: "Links de terceiros", content: "Não incluímos nem oferecemos serviços de terceiros no nosso site." },
  { title: "Google", content: "Os requisitos de publicidade do Google podem ser resumidos pelos Princípios de Publicidade do Google. Foram estabelecidos para proporcionar uma experiência positiva aos utilizadores. Utilizamos o Google AdSense no nosso site. O Google, como fornecedor terceiro, utiliza cookies para exibir anúncios no nosso site. A utilização do cookie DART pelo Google permite-lhe exibir anúncios aos nossos utilizadores com base em visitas anteriores ao nosso site e a outros sites na Internet. Os utilizadores podem optar por não utilizar o cookie DART visitando a política de privacidade da Rede de Conteúdo e Anúncios do Google." },
  { title: "Implementámos o seguinte:", content: "", items: ["Remarketing com Google AdSense", "Relatórios de Impressões da Rede de Display do Google"] },
  { title: "", content: "Nós, juntamente com fornecedores terceiros como o Google, utilizamos cookies próprios (como os cookies do Google Analytics) e cookies de terceiros (como o cookie DoubleClick) ou outros identificadores de terceiros em conjunto para compilar dados sobre as interações dos utilizadores com as impressões de anúncios e outras funções do serviço de anúncios relacionadas com o nosso site." },
  { title: "Exclusão voluntária", content: "Os utilizadores podem definir preferências sobre como o Google lhe anuncia utilizando a página de Configurações de Anúncios do Google. Alternativamente, pode optar por não participar visitando a página de Exclusão Voluntária da Iniciativa de Publicidade em Rede ou utilizando o complemento do navegador de Exclusão Voluntária do Google Analytics." },
  { title: "Lei de Proteção de Privacidade Online dos EAU", content: "O alcance da lei estende-se muito além dos EAU para exigir que qualquer pessoa ou empresa no CCG (e possivelmente no mundo) que opere sites que recolham Informações Pessoais Identificáveis de consumidores dos EAU publique uma política de privacidade visível no seu site indicando exatamente as informações que estão a ser recolhidas e as pessoas ou empresas com quem estão a ser partilhadas. De acordo com a lei, concordamos com o seguinte:", items: ["Os utilizadores podem visitar o nosso site anonimamente.", "Assim que esta política de privacidade for criada, adicionaremos um link para a mesma na nossa página inicial ou, no mínimo, na primeira página significativa após entrar no nosso site.", "O link da nossa Política de Privacidade inclui a palavra 'Privacidade' e pode ser facilmente encontrado na página especificada acima.", "Será notificado de quaisquer alterações à Política de Privacidade na nossa Página de Política de Privacidade.", "Pode alterar as suas informações pessoais enviando-nos um e-mail, conversando connosco ou enviando-nos um ticket de suporte."] },
  { title: "Como é que o nosso site lida com os sinais de Não Rastrear?", content: "Honramos os sinais de Não Rastrear e Não Rastrear, plantamos cookies ou utilizamos publicidade quando um mecanismo de navegador de Não Rastrear (DNT) está ativo." },
  { title: "O nosso site permite o rastreamento comportamental de terceiros?", content: "Também é importante notar que permitimos o rastreamento comportamental de terceiros." },
  { title: "COPPA (Lei de Proteção da Privacidade Infantil Online)", content: "Quando se trata da recolha de informações pessoais de crianças menores de 13 anos, a Lei de Proteção da Privacidade Infantil Online (COPPA) coloca os pais no controlo. A Comissão Federal de Comércio, a agência de proteção ao consumidor dos Estados Unidos, aplica a Regra COPPA, que detalha o que os operadores de sites e serviços online devem fazer para proteger a privacidade e segurança das crianças online. Não comercializamos especificamente para crianças menores de 13 anos." },
  { title: "Práticas de Informação Justa", content: "Os Princípios de Práticas de Informação Justa formam a espinha dorsal da lei de privacidade nos Estados Unidos e os conceitos que incluem desempenharam um papel significativo no desenvolvimento das leis de proteção de dados em todo o mundo. Compreender os Princípios de Práticas de Informação Justa e como devem ser implementados é fundamental para cumprir as várias leis de privacidade que protegem as informações pessoais. Para estar em conformidade com as Práticas de Informação Justa, tomaremos a seguinte ação de resposta, caso ocorra uma violação de dados:", items: ["Notificá-lo-emos por e-mail dentro de 1 dia útil."] },
  { title: "", content: "Também concordamos com o Princípio de Reparação Individual que exige que os indivíduos tenham o direito de perseguir legalmente direitos executórios contra os coletores e processadores de dados que não cumprem a lei. Este princípio exige não apenas que os indivíduos tenham direitos executórios contra os utilizadores de dados, mas também que os indivíduos tenham recurso a tribunais ou agências governamentais para investigar e/ou processar o não cumprimento por parte dos processadores de dados." },
  { title: "Que Dados Pessoais são Recolhidos e Como são Recolhidos", content: "Recolhemos informações suas quando se regista no nosso site, subscreve uma newsletter, preenche um formulário, utiliza o chat ao vivo ou insere informações no nosso site. Recolhemos dados pessoais, como endereços IP de visitantes, dos visitantes do nosso site utilizando tecnologias de rastreamento como cookies de terceiros e tecnologias não baseadas em cookies. Podemos usar as informações que recolhemos de si quando se regista, subscreve a nossa newsletter, responde a um inquérito ou comunicação de marketing, navega no site ou utiliza certas outras funcionalidades do site das seguintes formas:", items: ["Para personalizar a sua experiência e permitir-nos fornecer o tipo de conteúdo e ofertas de projetos em que está mais interessado.", "Para enviar e-mails periódicos sobre os seus interesses em projetos ou outros serviços.", "Para fazer follow-up após correspondência (chat ao vivo, e-mail ou consultas telefónicas)."] },
  { title: "Fins para os Quais os Dados são Utilizados e por Quem", content: "Recolhemos os seus e-mails para fins de marketing direto. Quando se regista, subscreve a nossa newsletter, participa num inquérito ou comunicação de marketing, navega no nosso site ou utiliza funcionalidades específicas, recolhemos informações suas. Estas informações são utilizadas das seguintes formas:", items: ["Personalização: Esforçamo-nos por adaptar a sua experiência e fornecer conteúdo e ofertas de projetos que se alinhem com os seus interesses.", "Comunicação: Enviamos e-mails periódicos sobre os seus interesses em projetos ou outros serviços valiosos.", "Follow-up: Contactamo-lo para fornecer assistência adicional e responder a quaisquer perguntas que possa ter, seja através de chat ao vivo, e-mail ou telefone."] },
  { title: "Como os Visitantes Podem Controlar a Recolha dos Seus Dados", content: "Note que pode controlar a recolha de dados através do seu navegador web e dispositivo móvel. Fornecemos as seguintes instruções para ajudar a exercer este controlo:" },
  { title: "Para Navegadores Web", content: "Recusar Cookies de Terceiros: Navegue até à função de configurações do seu navegador web e escolha rejeitar todos os cookies de terceiros. Alternativamente, pode recusar especificamente cookies de terceiros de sites específicos." },
  { title: "Para Dispositivos Móveis", content: "Limitar o Rastreamento de Anúncios: Aceda às configurações de privacidade no seu dispositivo móvel e localize a opção para limitar o rastreamento de anúncios. Ative esta configuração para restringir a recolha de dados para fins de publicidade direcionada. Repor o Identificador do Anunciante: Nas configurações de privacidade do seu dispositivo móvel, pode encontrar a opção para repor o identificador do anunciante. Esta ação irá repor o identificador único associado ao seu dispositivo, ajudando a limitar o rastreamento dos seus dados para publicidade direcionada." },
  { title: "Como usamos os Dados que recolhemos?", content: "O nosso objetivo é utilizar estes dados para o identificar e conectar consigo com precisão, oferecendo assim uma experiência online ideal onde o conteúdo suportado por anúncios seja acessível sem custos, e os anúncios que lhe são apresentados sejam relevantes e envolventes. Além disso, empregamos estes dados para operar, melhorar e aperfeiçoar os nossos serviços de forma eficaz." },
  { title: "Correspondência entre dispositivos", content: "Ao identificar vários dispositivos e navegadores associados a si, podemos direcionar, regular e sequenciar anúncios estrategicamente, permitindo-nos medir e analisar o desempenho da campanha de forma eficaz. Por exemplo, esta correspondência entre dispositivos permite-nos evitar mostrar-lhe anúncios de uma propriedade que já pesquisou num dispositivo, como o seu tablet, depois de os ter visto no seu telefone. Em vez disso, podemos apresentar-lhe anúncios de próximos lançamentos de propriedades onde possa utilizar esses interesses." },
  { title: "Segmentação de Audiências", content: "Empregamos técnicas de segmentação para categorizar indivíduos em grupos específicos com base nas suas informações demográficas e firmográficas ligadas ao seu identificador único. Esta segmentação permite-nos gerar relatórios perspicazes e realizar análises aprofundadas. Também nos ajuda a determinar os anúncios e conteúdos de e-mail mais relevantes que se alinham com os seus interesses específicos." },
  { title: "Lei CAN SPAM", content: "A Lei CAN-SPAM é uma lei que estabelece as regras para o e-mail comercial, estabelece requisitos para mensagens comerciais, concede aos destinatários o direito de parar de receber e-mails e estabelece penalizações severas por violações. Recolhemos o seu endereço de e-mail para estar em conformidade com a CAN-SPAM. Se a qualquer momento desejar cancelar a subscrição de receber futuros e-mails, pode enviar-nos um e-mail para info@offplan-dubai.com e removeremo-lo prontamente de TODA a correspondência." },
  { title: "Contacto", content: "Se tiver alguma dúvida sobre esta política de privacidade, pode contactar-nos utilizando as informações abaixo.\n\nEscritório #1802, 18.º Andar, Marina Plaza, Dubai Marina, Dubai, EAU\n\ninfo@providentestate.com" },
]

export function getPrivacyContent(locale: string): Section[] {
  const lang = locale === "ae" || locale === "en" || locale === "gb" ? "en" :
               locale === "br" || locale === "pt" ? "pt" : "es"
  return { en, es, pt }[lang] ?? en
}
