interface Section {
  title: string
  content: string
  items?: string[]
}

const en: Section[] = [
  { title: "1. Acceptance of Terms", content: "By accessing or using this website, you agree to be bound by these Terms & Conditions and our Privacy Policy. If you do not agree, please do not use the website." },
  { title: "2. Nature of Our Service", content: "We are not a real estate agency. We do not act as brokers, intermediaries, or representatives of buyers, sellers, tenants, or landlords. Our platform provides information about real estate projects and allows users to connect directly with developers. We do not participate in negotiations, transactions, payments, contracts, or viewings between users and developers." },
  { title: "3. Verified Projects", content: "All properties listed on our platform go through our internal verification policy before they are published. Verification is based on information provided by developers and third-party sources; however, we cannot guarantee accuracy, completeness, or availability at all times. Users must conduct their own due diligence before entering into any agreement with a developer or third party." },
  { title: "4. No Guarantees or Warranties", content: "Although we work to prevent fake listings, misrepresentation, and scam activity: We do not guarantee the authenticity or reliability of any developer, project, or offering. We are not liable for false, outdated, or misleading information provided by developers or third parties. Users interact with developers at their own risk." },
  { title: "5. User Responsibilities", content: "By using the website, you agree to: Provide accurate information when submitting inquiries or forms. Use the platform only for legitimate personal or commercial property research. Not engage in fraudulent, abusive, or harmful behavior. Not impersonate agents, developers, or individuals. Any misuse of the platform may result in account suspension or legal action." },
  { title: "6. Developer Responsibilities", content: "Developers listing properties on the platform agree to: Provide truthful, accurate, and updated information. Respond to user inquiries in good faith. Operate within the legal requirements of their country. We reserve the right to remove any developer or listing that violates these standards." },
  { title: "7. No Agency Relationship", content: "Using this platform does not create any partnership, employment, brokerage, or agency relationship between: You and the company, the company and developers, the company and third parties. We simply provide a technology platform for discovery and connection." },
  { title: "8. Limitation of Liability", content: "To the fullest extent permitted by law, Off Plan International is not liable for: Financial loss, misrepresentation by developers, inaccurate information, missed opportunities, project changes or cancellations, fraud, scam attempts, or misleading communication by developers or third parties. Any transaction carried out outside our platform. Users connect and transact at their own responsibility." },
  { title: "9. Third-Party Links", content: "Our website may contain links to external websites. We do not control, endorse, or guarantee the content or practices of those websites." },
  { title: "10. Intellectual Property", content: "All website content — including branding, logos, images, and text — is the property of Off Plan International, unless otherwise stated. Users may not reproduce, modify, or distribute any content without written permission." },
  { title: "11. Changes to These Terms", content: "We may update these Terms & Conditions at any time. Changes become effective once published on this page. Continued use of the website indicates acceptance of the updated terms." },
  { title: "12. Governing Law", content: "These Terms & Conditions are governed by the laws of Dubai, United Arab Emirates. Any disputes shall be resolved in the courts of Dubai, United Arab Emirates." },
]

const es: Section[] = [
  { title: "1. Aceptación de los Términos", content: "Al acceder o utilizar este sitio web, usted acepta estar sujeto a estos Términos y Condiciones y a nuestra Política de Privacidad. Si no está de acuerdo, no utilice el sitio web." },
  { title: "2. Naturaleza de Nuestro Servicio", content: "No somos una agencia inmobiliaria. No actuamos como corredores, intermediarios o representantes de compradores, vendedores, inquilinos o propietarios. Nuestra plataforma proporciona información sobre proyectos inmobiliarios y permite a los usuarios conectarse directamente con los desarrolladores. No participamos en negociaciones, transacciones, pagos, contratos o visitas entre usuarios y desarrolladores." },
  { title: "3. Proyectos Verificados", content: "Todas las propiedades listadas en nuestra plataforma pasan por nuestra política de verificación interna antes de ser publicadas. La verificación se basa en información proporcionada por los desarrolladores y fuentes externas; sin embargo, no podemos garantizar precisión, integridad o disponibilidad en todo momento. Los usuarios deben realizar su propia debida diligencia antes de llegar a cualquier acuerdo con un desarrollador o tercero." },
  { title: "4. Sin Garantías", content: "Aunque trabajamos para prevenir listados falsos, tergiversación y actividad fraudulenta: No garantizamos la autenticidad o confiabilidad de ningún desarrollador, proyecto u oferta. No somos responsables por información falsa, desactualizada o engañosa proporcionada por desarrolladores o terceros. Los usuarios interactúan con los desarrolladores bajo su propio riesgo." },
  { title: "5. Responsabilidades del Usuario", content: "Al utilizar el sitio web, usted acepta: Proporcionar información precisa al enviar consultas o formularios. Usar la plataforma solo para investigación legítima de propiedades personal o comercial. No participar en comportamiento fraudulento, abusivo o dañino. No hacerse pasar por agentes, desarrolladores o individuos. Cualquier mal uso de la plataforma puede resultar en suspensión de cuenta o acción legal." },
  { title: "6. Responsabilidades del Desarrollador", content: "Los desarrolladores que listan propiedades en la plataforma aceptan: Proporcionar información veraz, precisa y actualizada. Responder a las consultas de los usuarios de buena fe. Operar dentro de los requisitos legales de su país. Nos reservamos el derecho de eliminar cualquier desarrollador o listado que viole estos estándares." },
  { title: "7. Sin Relación de Agencia", content: "El uso de esta plataforma no crea ninguna relación de sociedad, empleo, corretaje o agencia entre: Usted y la empresa, la empresa y los desarrolladores, la empresa y terceros. Simplemente proporcionamos una plataforma tecnológica para descubrimiento y conexión." },
  { title: "8. Limitación de Responsabilidad", content: "En la máxima medida permitida por la ley, Off Plan International no es responsable por: Pérdidas financieras, tergiversación por parte de desarrolladores, información inexacta, oportunidades perdidas, cambios o cancelaciones de proyectos, fraude, intentos de estafa o comunicación engañosa por parte de desarrolladores o terceros. Cualquier transacción realizada fuera de nuestra plataforma. Los usuarios se conectan y realizan transacciones bajo su propia responsabilidad." },
  { title: "9. Enlaces a Terceros", content: "Nuestro sitio web puede contener enlaces a sitios web externos. No controlamos, respaldamos ni garantizamos el contenido o las prácticas de esos sitios web." },
  { title: "10. Propiedad Intelectual", content: "Todo el contenido del sitio web — incluyendo marca, logotipos, imágenes y texto — es propiedad de Off Plan International, a menos que se indique lo contrario. Los usuarios no pueden reproducir, modificar o distribuir ningún contenido sin permiso por escrito." },
  { title: "11. Cambios a Estos Términos", content: "Podemos actualizar estos Términos y Condiciones en cualquier momento. Los cambios entran en vigor una vez publicados en esta página. El uso continuado del sitio web indica la aceptación de los términos actualizados." },
  { title: "12. Ley Aplicable", content: "Estos Términos y Condiciones se rigen por las leyes de Dubái, Emiratos Árabes Unidos. Cualquier disputa se resolverá en los tribunales de Dubái, Emiratos Árabes Unidos." },
]

const pt: Section[] = [
  { title: "1. Aceitação dos Termos", content: "Ao aceder ou utilizar este site, concorda em ficar vinculado a estes Termos e Condições e à nossa Política de Privacidade. Se não concordar, não utilize o site." },
  { title: "2. Natureza do Nosso Serviço", content: "Não somos uma agência imobiliária. Não atuamos como corretores, intermediários ou representantes de compradores, vendedores, inquilinos ou proprietários. A nossa plataforma fornece informações sobre projetos imobiliários e permite que os utilizadores se conectem diretamente com os promotores. Não participamos em negociações, transações, pagamentos, contratos ou visitas entre utilizadores e promotores." },
  { title: "3. Projetos Verificados", content: "Todas as propriedades listadas na nossa plataforma passam pela nossa política de verificação interna antes de serem publicadas. A verificação baseia-se em informações fornecidas pelos promotores e fontes externas; no entanto, não podemos garantir precisão, integridade ou disponibilidade em todos os momentos. Os utilizadores devem realizar a sua própria diligência antes de celebrar qualquer acordo com um promotor ou terceiro." },
  { title: "4. Sem Garantias", content: "Embora trabalhemos para prevenir listagens falsas, distorções e atividades fraudulentas: Não garantimos a autenticidade ou fiabilidade de qualquer promotor, projeto ou oferta. Não somos responsáveis por informações falsas, desatualizadas ou enganosas fornecidas por promotores ou terceiros. Os utilizadores interagem com os promotores por sua própria conta e risco." },
  { title: "5. Responsabilidades do Utilizador", content: "Ao utilizar o site, concorda em: Fornecer informações precisas ao enviar consultas ou formulários. Utilizar a plataforma apenas para pesquisa legítima de propriedades pessoal ou comercial. Não se envolver em comportamentos fraudulentos, abusivos ou prejudiciais. Não se fazer passar por agentes, promotores ou indivíduos. Qualquer uso indevido da plataforma pode resultar em suspensão da conta ou ação legal." },
  { title: "6. Responsabilidades do Promotor", content: "Os promotores que listam propriedades na plataforma concordam em: Fornecer informações verdadeiras, precisas e atualizadas. Responder às consultas dos utilizadores de boa fé. Operar dentro dos requisitos legais do seu país. Reservamo-nos o direito de remover qualquer promotor ou listagem que viole estes padrões." },
  { title: "7. Sem Relação de Agência", content: "A utilização desta plataforma não cria qualquer relação de parceria, emprego, corretagem ou agência entre: Você e a empresa, a empresa e os promotores, a empresa e terceiros. Fornecemos simplesmente uma plataforma tecnológica para descoberta e conexão." },
  { title: "8. Limitação de Responsabilidade", content: "Na máxima extensão permitida por lei, a Off Plan International não é responsável por: Perdas financeiras, distorção por parte de promotores, informações imprecisas, oportunidades perdidas, alterações ou cancelamentos de projetos, fraude, tentativas de burla ou comunicação enganosa por parte de promotores ou terceiros. Qualquer transação realizada fora da nossa plataforma. Os utilizadores conectam-se e realizam transações por sua própria responsabilidade." },
  { title: "9. Links de Terceiros", content: "O nosso site pode conter links para sites externos. Não controlamos, endossamos ou garantimos o conteúdo ou práticas desses sites." },
  { title: "10. Propriedade Intelectual", content: "Todo o conteúdo do site — incluindo marca, logótipos, imagens e texto — é propriedade da Off Plan International, salvo indicação em contrário. Os utilizadores não podem reproduzir, modificar ou distribuir qualquer conteúdo sem autorização por escrito." },
  { title: "11. Alterações a Estes Termos", content: "Podemos atualizar estes Termos e Condições em qualquer momento. As alterações entram em vigor assim que publicadas nesta página. A utilização continuada do site indica aceitação dos termos atualizados." },
  { title: "12. Lei Aplicável", content: "Estes Termos e Condições regem-se pelas leis do Dubai, Emirados Árabes Unidos. Qualquer disputa será resolvida nos tribunais do Dubai, Emirados Árabes Unidos." },
]

export function getTermsContent(locale: string): Section[] {
  const lang = locale === "ae" || locale === "en" || locale === "gb" ? "en" :
               locale === "br" || locale === "pt" ? "pt" : "es"
  return { en, es, pt }[lang] ?? en
}
