-- Seed: Off Plan International community tags (carga unica desde CSV de Webflow)
-- Ejecutar despues de la migracion 009_community_tags_amenities.sql

INSERT INTO public.community_tags (name, slug, category)
VALUES
('Affordable living', 'affordable-living', 'Lifestyle & Living'),
('Airport proximity', 'airport-proximity', 'Transport & Connectivity'),
('Beach access', 'beach-access', 'Outdoor & Recreation'),
('Beachfront', 'beachfront', 'Location & Geography'),
('Business district', 'business-district', 'Work & Business'),
('Business hubs nearby', 'business-hubs-nearby', 'Work & Business'),
('Canal facing', 'canal-facing', 'Location & Geography'),
('Capital appreciation potential', 'capital-appreciation-potential', 'Investment & Buyer Appeal'),
('Car-friendly', 'car-friendly', 'Transport & Connectivity'),
('Child-friendly amenities', 'child-friendly-amenities', 'Family & Education'),
('City centre', 'city-centre', 'Location & Geography'),
('Close to offices', 'close-to-offices', 'Work & Business'),
('Community centres', 'community-centres', 'Amenities & Convenience'),
('Community focused', 'community-focused', 'Lifestyle & Living'),
('Corporate area', 'corporate-area', 'Work & Business'),
('Creekside', 'creekside', 'Location & Geography'),
('Cycling & jogging tracks', 'cycling-jogging-tracks', 'Outdoor & Recreation'),
('Desert-edge', 'desert-edge', 'Location & Geography'),
('Digital nomads', 'digital-nomads', 'Buyer Profile Tags'),
('Dining & cafés', 'dining-cafes', 'Amenities & Convenience'),
('Easy city access', 'easy-city-access', 'Transport & Connectivity'),
('End-user focused', 'end-user-focused', 'Investment & Buyer Appeal'),
('Entertainment district', 'entertainment-district', 'Amenities & Convenience'),
('Everyday convenience', 'everyday-convenience', 'Amenities & Convenience'),
('Expat-friendly', 'expat-friendly', 'Buyer Profile Tags'),
('Families', 'families', 'Buyer Profile Tags'),
('Family-friendly', 'family-friendly', 'Family & Education'),
('Family-oriented', 'family-oriented', 'Community Type & Feel'),
('First-time buyers', 'first-time-buyers', 'Buyer Profile Tags'),
('Freelancer-friendly', 'freelancer-friendly', 'Work & Business'),
('Gated community', 'gated-community', 'Community Type & Feel'),
('Golf community', 'golf-community', 'Outdoor & Recreation'),
('Green spaces', 'green-spaces', 'Outdoor & Recreation'),
('High rental demand', 'high-rental-demand', 'Investment & Buyer Appeal'),
('High-rise district', 'high-rise-district', 'Community Type & Feel'),
('Hospitals nearby', 'hospitals-nearby', 'Amenities & Convenience'),
('International schools nearby', 'international-schools-nearby', 'Family & Education'),
('Investor favourite', 'investor-favourite', 'Investment & Buyer Appeal'),
('Investors', 'investors', 'Buyer Profile Tags'),
('Island living', 'island-living', 'Location & Geography'),
('Lagoon community', 'lagoon-community', 'Location & Geography'),
('Lifestyle destination', 'lifestyle-destination', 'Community Type & Feel'),
('Long-term rental appeal', 'long-term-rental-appeal', 'Investment & Buyer Appeal'),
('Low-rise community', 'low-rise-community', 'Community Type & Feel'),
('Luxury living', 'luxury-living', 'Lifestyle & Living'),
('Major highway access', 'major-highway-access', 'Transport & Connectivity'),
('Marina access', 'marina-access', 'Outdoor & Recreation'),
('Marina living', 'marina-living', 'Location & Geography'),
('Master planned', 'master-planned', 'Community Type & Feel'),
('Metro access', 'metro-access', 'Transport & Connectivity'),
('Mid-market', 'mid-market', 'Lifestyle & Living'),
('Mixed-use', 'mixed-use', 'Community Type & Feel'),
('Modern lifestyle', 'modern-lifestyle', 'Lifestyle & Living'),
('Nightlife hub', 'nightlife-hub', 'Amenities & Convenience'),
('Nurseries nearby', 'nurseries-nearby', 'Family & Education'),
('Off-plan hotspot', 'off-plan-hotspot', 'Investment & Buyer Appeal'),
('Outdoor lifestyle', 'outdoor-lifestyle', 'Outdoor & Recreation'),
('Parks & playgrounds', 'parks-playgrounds', 'Outdoor & Recreation'),
('Pet-friendly', 'pet-friendly', 'Lifestyle & Living'),
('Public transport hub', 'public-transport-hub', 'Transport & Connectivity'),
('Quiet & residential', 'quiet-residential', 'Community Type & Feel'),
('Residential-focused', 'residential-focused', 'Community Type & Feel'),
('Resort-style living', 'resort-style-living', 'Community Type & Feel'),
('Retail within community', 'retail-within-community', 'Amenities & Convenience'),
('Retiree-friendly', 'retiree-friendly', 'Buyer Profile Tags'),
('Safe neighbourhood', 'safe-neighbourhood', 'Family & Education'),
('Schools nearby', 'schools-nearby', 'Amenities & Convenience'),
('Schools within community', 'schools-within-community', 'Family & Education'),
('Shopping malls nearby', 'shopping-malls-nearby', 'Amenities & Convenience'),
('Short-term rental friendly', 'short-term-rental-friendly', 'Investment & Buyer Appeal'),
('Sports facilities', 'sports-facilities', 'Outdoor & Recreation'),
('Strong ROI', 'strong-roi', 'Investment & Buyer Appeal'),
('Suburban', 'suburban', 'Location & Geography'),
('Traditional neighbourhood', 'traditional-neighbourhood', 'Lifestyle & Living'),
('Tram access', 'tram-access', 'Transport & Connectivity'),
('Ultra-luxury', 'ultra-luxury', 'Lifestyle & Living'),
('Urban', 'urban', 'Location & Geography'),
('Vibrant & lively', 'vibrant-lively', 'Community Type & Feel'),
('Walkable community', 'walkable-community', 'Lifestyle & Living'),
('Water sports nearby', 'water-sports-nearby', 'Outdoor & Recreation'),
('Waterfront', 'waterfront', 'Location & Geography'),
('Well-connected', 'well-connected', 'Transport & Connectivity'),
('Wellness focused', 'wellness-focused', 'Lifestyle & Living'),
('Work-live community', 'work-live-community', 'Work & Business'),
('Young professionals', 'young-professionals', 'Buyer Profile Tags')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  is_active = true;
