-- Seed: Off Plan International property amenities (carga unica desde CSV de Webflow)
-- Ejecutar despues de la migracion 009_community_tags_amenities.sql

INSERT INTO public.property_amenities (name, slug, icon_url, category)
VALUES
('24/7 security', '24-7-security', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee165d4a00eaaadec3306_shield.svg', 'Building & Resident Facilities'),
('ATM access', 'atm-access', NULL, 'Convenience & Retail'),
('Access control system', 'access-control-system', NULL, 'Safety & Accessibility'),
('Accessible units', 'accessible-units', NULL, 'Safety & Accessibility'),
('Airbnb-friendly building', 'airbnb-friendly-building', NULL, 'Investment & Rental-Friendly'),
('BBQ area', 'bbq-area', NULL, 'Outdoor & Community Spaces'),
('Balcony', 'balcony', NULL, 'Apartment / Unit Features'),
('Basement parking', 'basement-parking', NULL, 'Parking & Transport'),
('Basketball court', 'basketball-court', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edda6facb311f86f9daa1_court-basketball.svg', 'Fitness & Sports'),
('Bicycle parking', 'bicycle-parking', NULL, 'Parking & Transport'),
('Built-in wardrobes', 'built-in-wardrobes', NULL, 'Apartment / Unit Features'),
('Business Lounge', 'business-lounge', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed9107ee6325bfe69c54d_business-lounge.svg', 'Building & Resident Facilities'),
('CCTV surveillance', 'cctv-surveillance', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee17523d1725a823c5bf2_security-camera.svg', 'Building & Resident Facilities'),
('Canal view', 'canal-view', NULL, 'View & Location-Based'),
('Car wash area', 'car-wash-area', NULL, 'Parking & Transport'),
('Children’s play area', 'childrens-play-area', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee105cd3b15b0e58e678e_pinwheel.svg', 'Outdoor & Community Spaces'),
('Children’s pool', 'childrens-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('City skyline view', 'city-skyline-view', NULL, 'View & Location-Based'),
('Co-working space', 'co-working-space', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee30fd3dc633b26458942_desktop.svg', 'Building & Resident Facilities'),
('Community park', 'community-park', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee125763a9fc3d0444b20_park.svg', 'Outdoor & Community Spaces'),
('Concierge service', 'concierge-service', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee146b5b0b1e263173664_call-bell.svg', 'Building & Resident Facilities'),
('Convenience stores', 'convenience-stores', NULL, NULL),
('Covered parking', 'covered-parking', NULL, 'Parking & Transport'),
('Cycling track', 'cycling-track', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edf4b6cfc46b7df7ef1e5_person-simple-bike.svg', 'Fitness & Sports'),
('Daycare / nursery', 'daycare-nursery', NULL, 'Family & Kids'),
('Dog park', 'dog-park', NULL, 'Pet-Friendly'),
('EV charging stations', 'ev-charging-stations', NULL, 'Parking & Transport'),
('Emergency power backup', 'emergency-power-backup', NULL, 'Safety & Accessibility'),
('Energy-efficient design', 'energy-efficient-design', NULL, 'Sustainability & Smart Living'),
('Family seating areas', 'family-seating-areas', NULL, 'Family & Kids'),
('Fire safety systems', 'fire-safety-systems', NULL, 'Safety & Accessibility'),
('Floor-to-ceiling windows', 'floor-to-ceiling-windows', NULL, 'Apartment / Unit Features'),
('Fully equipped gym', 'fully-equipped-gym', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edd3c6c751f05a6a6d539_barbell.svg', 'Fitness & Sports'),
('Fully fitted kitchen', 'fully-fitted-kitchen', NULL, 'Apartment / Unit Features'),
('Golf course view', 'golf-course-view', NULL, 'View & Location-Based'),
('Holiday home permitted', 'holiday-home-permitted', NULL, 'Investment & Rental-Friendly'),
('Indoor play area', 'indoor-play-area', NULL, 'Family & Kids'),
('Indoor pool', 'indoor-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('Infinity pool', 'infinity-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('Jacuzzi / hot tub', 'jacuzzi-hot-tub', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edcad6e18696e3656c91d_bathtub.svg', 'Leisure & Lifestyle'),
('Jogging track', 'jogging-track', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696eddfa6d655f9fb5ab85c3_person-simple-run.svg', 'Fitness & Sports'),
('Kids’ playroom', 'kids-playroom', NULL, 'Family & Kids'),
('Landscaped gardens', 'landscaped-gardens', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed90946217bb4d9196aa4_rooftop-garden.svg', 'Outdoor & Community Spaces'),
('Laundry room', 'laundry-room', NULL, 'Apartment / Unit Features'),
('Library / reading room', 'library-reading-room', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee352d71cd600f2bcf8ea_books.svg', 'Building & Resident Facilities'),
('Lobby lounge', 'lobby-lounge', NULL, 'Building & Resident Facilities'),
('Luxury Pool', 'luxury-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('Maid’s room', 'maids-room', NULL, 'Apartment / Unit Features'),
('Marina view', 'marina-view', NULL, 'View & Location-Based'),
('Meditation area', 'meditation-area', NULL, 'Leisure & Lifestyle'),
('Meeting rooms', 'meeting-rooms', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee3368458304233fd0e58_presentation-chart.svg', 'Building & Resident Facilities'),
('Multi-purpose court', 'multi-purpose-court', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edda6facb311f86f9daa1_court-basketball.svg', 'Fitness & Sports'),
('On-site property management', 'on-site-property-management', NULL, 'Investment & Rental-Friendly'),
('Outdoor gym', 'outdoor-gym', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edd3c6c751f05a6a6d539_barbell.svg', 'Fitness & Sports'),
('Padel court', 'padel-court', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edd8122b0df2cc6eda7bc_racquet.svg', 'Fitness & Sports'),
('Park view', 'park-view', NULL, 'View & Location-Based'),
('Personal training studio', 'personal-training-studio', NULL, 'Fitness & Sports'),
('Pet washing station', 'pet-washing-station', NULL, 'Pet-Friendly'),
('Pet-friendly building', 'pet-friendly-building', NULL, 'Pet-Friendly'),
('Pharmacy nearby', 'pharmacy-nearby', NULL, 'Convenience & Retail'),
('Picnic areas', 'picnic-areas', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee0e534f34b3d925f7013_picnic-table.svg', 'Outdoor & Community Spaces'),
('Premium appliances', 'premium-appliances', NULL, 'Apartment / Unit Features'),
('Private garden', 'private-garden', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed90946217bb4d9196aa4_rooftop-garden.svg', 'Apartment / Unit Features'),
('Private pool', 'private-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('Reception desk', 'reception-desk', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ee2ec714a6c90a5f0744b_desk.svg', 'Building & Resident Facilities'),
('Recycling facilities', 'recycling-facilities', NULL, 'Sustainability & Smart Living'),
('Rental management services', 'rental-management-services', NULL, 'Investment & Rental-Friendly'),
('Residents lounge', 'residents-lounge', NULL, 'Building & Resident Facilities'),
('Retail outlets on-site', 'retail-outlets-on-site', NULL, 'Convenience & Retail'),
('Rooftop Garden', 'rooftop-garden', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed90946217bb4d9196aa4_rooftop-garden.svg', 'Outdoor & Community Spaces'),
('Sauna', 'sauna', NULL, 'Leisure & Lifestyle'),
('Sea view', 'sea-view', NULL, 'View & Location-Based'),
('Short-term rental friendly', 'short-term-rental-friendly', NULL, 'Investment & Rental-Friendly'),
('Shuttle service', 'shuttle-service', NULL, 'Parking & Transport'),
('Sky lounge', 'sky-lounge', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed9107ee6325bfe69c54d_business-lounge.svg', 'Outdoor & Community Spaces'),
('Smart access control', 'smart-access-control', NULL, 'Sustainability & Smart Living'),
('Smart home system', 'smart-home-system', NULL, 'Apartment / Unit Features'),
('Smart lighting', 'smart-lighting', NULL, 'Sustainability & Smart Living'),
('Solar panels', 'solar-panels', NULL, 'Sustainability & Smart Living'),
('Spa & wellness centre', 'spa-wellness-centre', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edcbf70bc35c55e744dee_sparkle.svg', 'Leisure & Lifestyle'),
('Splash pad', 'splash-pad', NULL, 'Outdoor & Community Spaces'),
('Sports courts', 'sports-courts', NULL, 'Fitness & Sports'),
('Steam room', 'steam-room', NULL, 'Leisure & Lifestyle'),
('Stroller-friendly access', 'stroller-friendly-access', NULL, 'Family & Kids'),
('Supermarket nearby', 'supermarket-nearby', NULL, 'Convenience & Retail'),
('Swimming pool', 'swimming-pool', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696ed902c911aeaaf0a30d66_swimming-pool.svg', 'Leisure & Lifestyle'),
('Tennis court', 'tennis-court', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696eddd64acd06eaa723269e_tennis-ball.svg', 'Fitness & Sports'),
('Terrace', 'terrace', NULL, 'Apartment / Unit Features'),
('Valet parking', 'valet-parking', NULL, 'Parking & Transport'),
('Visitor parking', 'visitor-parking', NULL, 'Parking & Transport'),
('Walk-in closet', 'walk-in-closet', NULL, 'Apartment / Unit Features'),
('Walking areas for pets', 'walking-areas-for-pets', NULL, 'Pet-Friendly'),
('Walking paths', 'walking-paths', NULL, 'Outdoor & Community Spaces'),
('Waste management system', 'waste-management-system', NULL, 'Sustainability & Smart Living'),
('Water-saving systems', 'water-saving-systems', NULL, 'Sustainability & Smart Living'),
('Waterfront access', 'waterfront-access', NULL, 'View & Location-Based'),
('Wheelchair access', 'wheelchair-access', NULL, 'Safety & Accessibility'),
('Yoga studio', 'yoga-studio', 'https://cdn.prod.website-files.com/68ada6f5bc65af392b69f8d7/696edd1f9e4baee72cd132a8_person-simple-tai-chi.svg', 'Leisure & Lifestyle')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon_url = EXCLUDED.icon_url,
  category = EXCLUDED.category,
  is_active = true;
